# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dollarjobs Blog
author: Dollarjobs
email: support@dollarjobs.co
description: >- # this means to ignore newlines until "baseurl:"
  Dollarjobs is the largest sales jobs board on the planet

google_analytics: UA-138035813-1
google-site-verification: Hpg3YxUIJoI1UrcNtRwRsa8FfLEs71b7fvO0tsmP80E
disqus:
  shortname: dollarjobs

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  # generate social links in footer
  social_links:
    twitter: dollarjobs108
    github:  dollarjobs108
    rss: rss
    # dribbble: jekyll
    facebook: dollarjobs108
    # flickr:   jekyll
    instagram: dollarjobs108
    linkedin: dollarjobs108
    pinterest: dollarjobs108
    # youtube: rightapp4u
    # youtube_channel: UCnA6j9YDsvxceohL9te64-Q
    # youtube_channel_name: RightApp4u
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://www.dollarjobs.co" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
theme: minima
permalink: /:title/
header_pages:
  - subscribe.md
show_excerpts: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
